### ISSUE TITLE
WebUI v2.3.0

### ISSUE THREAD

**Issue by hassandraga** [webui-dev/v-webui#12]
WebUI v2.3.0 is pushed to the main branch.
https://github.com/alifcommunity/webui/commit/ca7b4f50ed8eb52c2f92bbd2b066e5498e329337

The only difference from v2.2.0 on the side of the wrappers is:
* The window object changed from `void*` (pointer) to a simple `size_t` (integer)
* License changed from `GPLv2` to 'MIT'

**Comment by malisipi** [comment]
I was updated to latest WebUI at the moment.
