### ISSUE TITLE
Any plans to add http client?

### ISSUE THREAD

**Issue by cyclecraze** [webui-dev/v-webui#14]
https://mongoose.ws/documentation/tutorials/http-client/

**Comment by AlbertShown** [comment]
Do you mean an API to read the content of an HTTP link?
something like `output = get_contents("https://domain.com/foo/bar.html")`

**Comment by cyclecraze** [comment]
Correct. Mongoose does have this ability, maybe it can be exposed to vlang. Possibly interact with forms on pages, inject javascript, navigate to a new page, etc.. It could be a great tool for automated testing, etc.

**Comment by AlbertShown** [comment]
In this case, using a real web browser is your best choice.

UI JavaScript:
```js
function get_http_content(theUrl) {
    var xmlHttp = new XMLHttpRequest();
    xmlHttp.open("GET", theUrl, false);
    xmlHttp.send(null);
    return xmlHttp.responseText;
}
```

Backend V:
```v
fn my_function(e &webui.Event) {
  // Execute a JavaScript and get back the response
  // 30 is the timeout in seconds
  // 1024 is the expected response buffer size
  response := e.window.script(" return get_http_content('https://domain.com/foo/bar.html'); ", 30, 1024)
}
```

**Comment by AlbertShown** [comment]
> Possibly interact with forms on pages, inject javascript, navigate to a new page, etc..

Yes. You can actually easily do that using JavaScript

```v
mut my_window := webui.new_window()
my_window.show(_HTML_HERE_)
my_window.script("_YOUR_JAVSCRIPT_HERE_", _TIME_OUT_HERE_, _EXPECTED_RESPONSE_SIZE_HERE_)
webui.wait()
```

**Comment by cyclecraze** [comment]
Thanks.

**Comment by malisipi** [comment]
If you need to fetch resources from internet, you can use net.http module from vlib (V's standart library).

**Comment by AlbertShown** [comment]
Yep, `net.http` from the V STD is another way. Which does not need to create the UI JavaScript `get_http_content()`.
