### ISSUE TITLE
First software using V-WebUI

### ISSUE THREAD

**Issue by hassandraga** [webui-dev/v-webui#19]
I want to let you know that I'm working on a _nice-looking_ text editor in C using WebUI. When it is ready, I will share it with you to be the first real software example using V-WebUI. You have to change the _OpenFile_ dialogue from C to V only.

**Comment by malisipi** [comment]
I'm waiting the application. Lmk when you release it!

**Comment by malisipi** [comment]
I'm currently porting text editor to V 1c2e30072c046e86c70c8ade06e3253915e57402

**Comment by malisipi** [comment]
Port is finished! d88798ab7f1d08b062f018c69205a0d0a17d5a8d.
