### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by hassandraga** [webui-dev/v-webui#25]
The next version `2.4.0` will include TLS Encryption between the GUI and the V application. This will make compiling WebUI from the source more challenging for the V wrapper.

I suggest making the V wrapper using the static pre-built library which makes things very easy as it does not need to compile WebUI from the source.

**Comment by ttytm** [comment]
I started using webui, feel thankful for having it and plan to continue using it so I could take care of integrating this if that's okay for you.

**Comment by AlbertShown** [comment]
Of course, you are welcome to make any contribution you would like 👍
Just to let you know, the TLS implementation can be done only with the WebUI [Core repo](https://github.com/webui-dev/webui), and it seems @hassandraga did it a while ago, but I don't know why it did not merge with the main branch until now.

Branche: https://github.com/webui-dev/webui/tree/WebUI-v2.4.0
TLS Commit: https://github.com/webui-dev/webui/commit/dd57446a301a9d425c98219b904a7f2a6bb736ef

**Comment by ttytm** [comment]
Thanks for your reply @AlbertShown!

Yes, I've seen it :). Linux and macOS is not ready yet. With my comment I thought to work on the switch to prebuilts. But regarding the issues title and marking it closed by PR, I'm a bit off, I realize. It's more part 1/2, swithcing to the prebuilt libs so it's easy to use the upcoming TLS feature.

**Comment by hassandraga** [comment]
Yes, The TLS is already implemented. I will merge it after we finish the one `makefile` implementation.

https://github.com/webui-dev/webui/pull/155
