### ISSUE TITLE
WebUI v2.2.0

### ISSUE THREAD

**Issue by hassandraga** [webui-dev/v-webui#5]
[WebUI v2.2.0](https://github.com/alifcommunity/webui/tree/WebUI_v2.2.0) is ready for release.

Big changes:

1. Now, `webui.h` it's become more straightforward and smaller and optimized for wrapper creation
2. `webui_show()` will replace `webui_open()` and `webui_new_server()`
3. `webui_window_t` struct becomes a simple `void*`
4. To solves the complexity of memory leaks when executing JS, now, the wrapper creates a local buffer and passes it to `webui_script()`
5. All core internal functions are removed from `webui.h`

To create the new V wrapper, run `c2v webui.h`. And remove all other functions from the old version v2.1.1.
After that, we will start creating more big software in V as an example (_Text editor, Media Player, Database viewer..._), which will be very exciting to explore and learn new things!.

If you have any questions, please don't hesitate to ask me here.
Thank you for maintaining the WebUI V wrapper. I appreciate it 👍

**Comment by malisipi** [comment]
I'm glad to hear that. 

`c2v webui.h` is good to make wrapper however it's not enough for supporting native datatypes and having more native functions.

```v
// C2V Wrapper
fn vwebui.webui_new_window() voidptr
fn vwebui.webui_is_shown(window voidptr) bool
fn vwebui.webui_show(window voidptr, content &i8) bool 
 // Example call: vwebui.webui_show(window, &char(content.str))

// Maded with hand
fn vwebui.new_window() Window_t
fn (window) is_shown() bool
fn (window) show ()
 // Example call: window.show(content)
```

`we will start creating more big software in V as an example (Text editor, Media Player, Database viewer...), `

Wow, I like it!

Thanks for all. I'm working currently on supporting Webui 2.2.0.
