### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by hassandraga** [webui-dev/v-webui#58]
```
# v install https://github.com/webui-dev/v-webui

Installing module "webui-dev\v-webui" from "https://github.com/webui-dev/v-webui" to "C:\Users\HD\.vmodules\webui_dev\v_webui" ...
Relocating module from "webui-dev\v-webui" to "vwebui" ( "C:\Users\HD\.vmodules\vwebui" ) ...
Module "webui-dev\v-webui" relocated to "vwebui" successfully.

# v run $HOME/.vmodules/vwebui/setup.vsh

v expects that `$HOME/.vmodules/vwebui/setup.vsh` exists, but it does not
```

I guess, in Windows it should be `%userprofile%` instead of `$HOME`.

```
# v run %userprofile%/.vmodules/vwebui/setup.vsh

Cloning...
git clone --depth 1 https://github.com/webui-dev/webui

Building...
"Build WebUI library (gcc release static)..." 
"Build WebUI library (gcc release dynamic)..." 
"Done."
```

**Comment by ttytm** [comment]
Thanks for the report. Yes %userprofile% $HOME apparently does only work in CI. It was also set on my fairly blank windows VM 🤔

**Comment by hassandraga** [comment]
If we cannot fix this by code, then simply we create `setup_ci.vsh` as a workaround 🤦‍♂️

**Comment by ttytm** [comment]
Yes, I check this quickly. There already is a comptime flag `v -d ci run setup.vsh` that uses another temp dir in Windows CI. So in one or the other way, we will be able to solve it.

**Comment by ttytm** [comment]
It's just the installation steps in the readme that need the fix, it's not used in the script. What I ment above was that $HOME works apparently only in CI out of the box on windows, and not on every machine. `%USERPROFILE%` would probably also work in CI.
