### ISSUE TITLE
Download pre-built instead of building from source

### ISSUE THREAD

**Issue by hassandraga** [webui-dev/v-webui#59]
```
# v run %userprofile%/.vmodules/vwebui/setup.vsh 
Cloning...
git clone --depth 1 https://github.com/webui-dev/webui

Building...
"Build WebUI library (gcc release static)..." 
"Build WebUI library (gcc release dynamic)..." 
"Done."
```

I suggest downloading the pre-built binaries from upstream repo instead of building it from source. For two reasons:
- The the pre-built binaries are built by CI, so it's trusted and safe
- The user must have GCC, and we know that TCC has issues

**Comment by ttytm** [comment]
Yes that's the plan 🙂👍. Bulding was added as a temporary step until the prebuilds are available as release and to relatively easily keep up with latest webui master. Looking into programmatically download github artifacts that were build by CI I only found ways that require adding a github authentication token when they are not released.

**Comment by ttytm** [comment]
~~We can add the required authentication as default maybe until the release. It could print an info with a link where prebuilds can be manually downloaded if a user doesn't want to authenticate and bulding as it is now, as a sub command.~~

Prorbaly too much effort as it would also serve just as a temporary solution. So maybe it's okay until releases are available. Then downloads can be made with a few line script. If other wrappers use prebuilts it can be a shell script.

**Comment by hassandraga** [comment]
Sorry, I forgot that it is just temporary. So yeah, sure, let's do this when releases are available.
