### ISSUE TITLE
Error: declaration for parameter 'webui_new_window' but no such parameter

### ISSUE THREAD

**Issue by gilmartaj** [webui-dev/v-webui#75]
Hello, I tried to run the examples and got the following error: 

**In file included from /tmp/v_1000/main.16722958108676249408.tmp.c:817:
/home/user/.vmodules/vwebui/webui/include/webui.h:158: error: declaration for parameter 'webui_new_window' but no such parameter**

Can someone help me?

**Comment by ttytm** [comment]
Hey @gilmartaj,

to help you better, can you share the following information?

- What example do you try to run?
- What is the output of `v doctor`?
- The newest version currently is not released, it's required to run the latest development version, are you using the latest commit and have run the setup after cloning / pulling?

**Comment by Dialga** [comment]
I just encountered this error too, on the latest v commit and master branch of v-webui. Arch Linux x64.

**Comment by ttytm** [comment]
Hey @Dialga thanks for reporting.

Thanks for reporting. I can reproduce it. Gonna look into it.

**Comment by ttytm** [comment]
It's an issue with TCC with the latest webui and V versions.

You should be able to compile when using `-cc gcc` or `-cc clang`
