### ISSUE TITLE
setLogging not desactivated before exit

### ISSUE THREAD

**Issue by StephaneTy-Pro** [webui-dev/v-webui#81]
### Description

If webui.setLogging() was set to true ; you must get it back to false before using exit() ; else browser window will not close but hang

### Expected Behavior

logging was set to false automatically before exit.

### Reproduction Steps

create an html + js [onload] which launch setlogging(true) 
and a button quit which launch webui.exit

click button quit

### Possible Solution

Systematically execute a clean script which set log to false before exit vwebui

### Version

2.5.0-beta2

### Environment Details (OS name, version, etc.)

```shell
windows 10 / intel 64
```

**Comment by AlbertShown** [comment]
I see what you mean. Yes, if the browser debugging console (DevTools) is activated, webui automatically prevents the window from closing. This is to let the developer see the last action logs for debugging purposes. This was useful during the development of webui.

However, the developer can simply disable the logs before exit:

```js
webui.setLogging(false);
my_backend_exit_function(); // or simply use JavaScript: close(); or window.close();
```

**Comment by StephaneTy-Pro** [comment]
yes, the problem is that because it was not documented, i could'nt found why app hang ... until i used webui.setLogging(false);

**Comment by AlbertShown** [comment]
I agree, this should be mentioned in the documentation.

**Comment by StephaneTy-Pro** [comment]
thanks
